import { POLYGON_SHAPES, isPolygon, type PrinterSettings } from '../types'
import { LIP_HEIGHT, type Compartment, type ModuleSpec, type PrintVariant } from './packing'

const n = (v: number) => {
  const r = Math.round(v * 1000) / 1000
  return Object.is(r, -0) ? '0' : String(r)
}

/** cavity snippet relative to the compartment's bounding-box corner */
function scadCavity(c: Compartment, height: number, cc: number): string {
  if (c.shape === 'circle') {
    return `translate([${n(c.length / 2)}, ${n(c.width / 2)}, 0]) cylinder(h=${n(height)}, r=${n(c.shapeDim / 2 + cc)}, $fn=64);`
  }
  if (isPolygon(c.shape)) {
    const def = POLYGON_SHAPES[c.shape]
    const R = c.shapeDim * def.radius + cc / Math.cos(Math.PI / def.sides)
    const rot = def.rotation + (c.rotated ? 90 : 0)
    return `translate([${n(c.length / 2)}, ${n(c.width / 2)}, 0]) rotate([0, 0, ${n(rot)}]) cylinder(h=${n(height)}, r=${n(R)}, $fn=${def.sides});`
  }
  return `cube([${n(c.length)}, ${n(c.width)}, ${n(height)}]);`
}

/**
 * Generate editable OpenSCAD source for one print variant. Opens directly in
 * OpenSCAD (or any tool that reads .scad): tweak the values, press F6 to
 * render, then export STL/3MF/AMF from there.
 */
export function moduleToScad(spec: ModuleSpec, variant: PrintVariant, s: PrinterSettings): string {
  const L = variant.outer.length
  const W = variant.outer.width
  const H = variant.outer.height
  const cc = s.componentClearance
  const wall = s.wallThickness

  const head = [
    `// ${variant.name} — generated by Board Game Organizer`,
    `// All dimensions in mm. Edit, render (F6), then export from OpenSCAD.`,
    `// Settings used: wall=${n(wall)} floor=${n(s.floorThickness)} piece_clearance=${n(cc)} lid_clearance=${n(s.lidClearance)}`,
    ``,
  ]

  if (spec.type === 'spacer') {
    const rects = spec.rects?.length ? spec.rects : [{ x: 0, y: 0, l: L, w: W }]

    if (spec.removeInnerWalls && rects.length > 1 && H > s.floorThickness + 2) {
      const cubes = rects
        .map((r) => `    translate([${n(r.x)}, ${n(r.y)}, ${n(s.floorThickness)}]) cube([${n(r.l)}, ${n(r.w)}, ${n(H)}]);`)
        .join('\n')
      return [
        ...head,
        `// Combined spacer hollowed as one open shell (inner walls removed):`,
        `// the cavity is the footprint eroded by the wall thickness.`,
        `module footprint() {`,
        `  union() {`,
        cubes,
        `  }`,
        `}`,
        `module cavity_x() { intersection() { translate([${n(wall)}, 0, 0]) footprint(); translate([${n(-wall)}, 0, 0]) footprint(); } }`,
        `module cavity() { intersection() { translate([0, ${n(wall)}, 0]) cavity_x(); translate([0, ${n(-wall)}, 0]) cavity_x(); } }`,
        `difference() {`,
        `  union() {`,
        rects
          .map((r) => `    translate([${n(r.x)}, ${n(r.y)}, 0]) cube([${n(r.l)}, ${n(r.w)}, ${n(H)}]);`)
          .join('\n'),
        `  }`,
        `  cavity();`,
        `}`,
        ``,
      ].join('\n')
    }

    const lines = [...head, `// Hollow spacer that fills a gap in the game box`, `union() {`]
    for (const r of rects) {
      lines.push(`  translate([${n(r.x)}, ${n(r.y)}, 0]) difference() {`)
      lines.push(`    cube([${n(r.l)}, ${n(r.w)}, ${n(H)}]);`)
      if (r.l > 2 * wall + 4 && r.w > 2 * wall + 4 && H > s.floorThickness + 2) {
        lines.push(
          `    translate([${n(wall)}, ${n(wall)}, ${n(s.floorThickness)}]) cube([${n(r.l - 2 * wall)}, ${n(r.w - 2 * wall)}, ${n(H + 1)}]);`,
        )
      }
      lines.push(`  }`)
    }
    lines.push(`}`, ``)
    return lines.join('\n')
  }

  if (spec.type === 'stack-tray' || spec.type === 'well') {
    const c = spec.compartments[0]
    const floorZ = H - c.depth
    const cavX = (L - c.length) / 2
    const cavY = (W - c.width) / 2
    const notchW = Math.min(20, c.width * 0.6)
    const notchBottom = floorZ + Math.max(2, c.depth * 0.25)
    return [
      ...head,
      `// ${spec.type === 'well' ? 'Well: pieces stand on edge' : 'Stack tray: pieces lie flat'} (${c.label})`,
      `difference() {`,
      `  cube([${n(L)}, ${n(W)}, ${n(H)}]);`,
      `  // cavity (floor at z=${n(floorZ)})`,
      `  translate([${n(cavX)}, ${n(cavY)}, ${n(floorZ)}]) ${scadCavity(c, c.depth + 1, cc)}`,
      `  // finger notches through both end walls`,
      `  translate([-1, ${n((W - notchW) / 2)}, ${n(notchBottom)}]) cube([${n(L + 2)}, ${n(notchW)}, ${n(H)}]);`,
      `}`,
      ``,
    ].join('\n')
  }

  // ----- lidded box: body + lid side by side -----
  const bodyH = H
  const lipT = Math.min(wall, 1.6)
  const plateT = s.floorThickness
  const inL = L - 2 * wall
  const inW = W - 2 * wall
  const band = lipT + 2 * s.lidClearance + 0.2
  const lipOuterL = inL - 2 * s.lidClearance
  const lipOuterW = inW - 2 * s.lidClearance
  const lipH = LIP_HEIGHT - 0.3

  const lines = [...head, `// ---- box body ----`, `difference() {`, `  cube([${n(L)}, ${n(W)}, ${n(bodyH)}]);`]
  for (const c of spec.compartments) {
    const x = wall + variant.extra.length / 2 + c.x
    const y = wall + variant.extra.width / 2 + c.y
    const z0 = bodyH - LIP_HEIGHT - c.depth
    lines.push(
      `  // ${c.label} (${c.quantity} pcs)`,
      `  translate([${n(x)}, ${n(y)}, ${n(z0)}]) ${scadCavity(c, c.depth + LIP_HEIGHT + 1, cc)}`,
    )
  }
  lines.push(`  // lip channel around the interior perimeter`)
  if (inL - 2 * band > 0.5 && inW - 2 * band > 0.5) {
    lines.push(
      `  translate([${n(wall)}, ${n(wall)}, ${n(bodyH - LIP_HEIGHT)}]) difference() {`,
      `    cube([${n(inL)}, ${n(inW)}, ${n(LIP_HEIGHT + 1)}]);`,
      `    translate([${n(band)}, ${n(band)}, -1]) cube([${n(inL - 2 * band)}, ${n(inW - 2 * band)}, ${n(LIP_HEIGHT + 3)}]);`,
      `  }`,
    )
  } else {
    lines.push(
      `  translate([${n(wall)}, ${n(wall)}, ${n(bodyH - LIP_HEIGHT)}]) cube([${n(inL)}, ${n(inW)}, ${n(LIP_HEIGHT + 1)}]);`,
    )
  }
  lines.push(`}`, ``, `// ---- lid (printed plate-down) ----`, `translate([${n(L + 10)}, 0, 0]) union() {`)
  lines.push(`  cube([${n(L)}, ${n(W)}, ${n(plateT)}]);`)
  if (lipOuterL > 1 && lipOuterW > 1) {
    lines.push(
      `  translate([${n((L - lipOuterL) / 2)}, ${n((W - lipOuterW) / 2)}, ${n(plateT)}]) difference() {`,
      `    cube([${n(lipOuterL)}, ${n(lipOuterW)}, ${n(lipH)}]);`,
    )
    if (lipOuterL - 2 * lipT > 0.5 && lipOuterW - 2 * lipT > 0.5) {
      lines.push(
        `    translate([${n(lipT)}, ${n(lipT)}, -1]) cube([${n(lipOuterL - 2 * lipT)}, ${n(lipOuterW - 2 * lipT)}, ${n(lipH + 2)}]);`,
      )
    }
    lines.push(`  }`)
  }
  lines.push(`}`, ``)
  return lines.join('\n')
}
